---
title: "見出しタイトル（目次には表示されない）"
output:
  html_document:
    df_print: paged
    code_folding: none
    css: style.css
---

<!-- shared Links -->
```{r index, child="../shared/links.Rmd", include=FALSE}
```

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
require(tidyverse)

# r_version <- paste("R v", R.version$major, ".", R.version$minor, sep = "")
r_version <- R.version$version.string
```

（前説をここに記載する）  
　  
なお、本ページでは`r r_version`の標準パッケージ以外に以下の追加パッケージを用いています。  
　  

Package   | Version |Description
----------|---------|----------------------------------------------------------
tidyverse | `r packageVersion('tidyverse')` | Easily Install and Load the ‘Tidyverse’


また、本ページでは以下のデータセットを用いています。  
　  

Dataset    | Package  | Version | Description
-----------|----------|---------|----------------------------------------------
airquality | datasets | `r packageVersion('datasets')`| New York Air Quality Measurements

　  

# 本文

　  

# 参考資料

* [ <i class="fa fa-external-link"></i>](){target="_blank" title=""}

　  

---

<!-- Footer -->
```{r child="../shared/footer.Rmd"}
```