---
title: "第３回データ分析勉強会"
author: "【午後の部】効率的で綺麗な可視化 [鈴木さんぽう, CC BY-NC-SA 4.0]"
date: "`r format(Sys.Date(), format = '%Y年%m月%d日')`"
output:
  ioslides_presentation:
    df_print: paged
    logo: ./fig/ggplot2.png
    smaller: false
    widescreen: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

require(tidyverse)
```


## 本日の内容
1. 効率的で綺麗な可視化（午前）
    * 整然データ（tidy data）と可視化
    * ggplot2を使ってみる
1. **効率的で綺麗な可視化（午後）**
    * 演習

# 効率的で綺麗な可視化

# 演習

## アンスコムのデータ例をグラフ化する
```{r, echo=FALSE}
anscombe %>%
  tibble::rownames_to_column("id") %>%
  tidyr::gather(key, value, -id) %>%
  tidyr::separate(key, c("axis", "group"), 1) %>%
  tidyr::spread(axis, value) %>% 
  ggplot2::ggplot(ggplot2::aes(x, y))+
    ggplot2::geom_point()+
    ggplot2::geom_smooth(method = lm, se = FALSE, fullrange = TRUE)+
    ggplot2::facet_wrap(~ group, nrow = 2)
```

## ヒント
やりたいこと           | 利用する関数例                      | 備考
-----------------------|-------------------------------------|---
整然データにする       | [第２回資料](./02_guidance_am.html) | 
散布図を描く           | **`ggplot2::geom_point()`**         | 
回帰線を描く           | **`ggplot2::geom_smooth()`**        |
層別に描く             | **`ggplot2::facet_wrap()`**         | 

## オープン・クローズチャートを描く
Redmineのチケットデータからチケットのオープン・クローズチャートを描いてみましょう。  

1. "Defect"（バグ）チケット1,000チケットが[対象データ](./redmine_data_utf8.csv)です
1. 日付の実態は日時（開始・終了日時）なので日に変換する必要があります
1. 対象データ期間を調べ日付範囲のデータフレームを作成します
1. 日付範囲を用いてチケット数の集計を行います
    * チケットオープン（開始日）、チケットクローズ（終了日）
    * 集計のNAデータは0に変換することをお忘れなく
1. 集計データから累計を計算します
1. 累計を折れ線グラフとして色分け表示します

## 描画例
```{r, echo=FALSE, fig.height=5}
# "./redmine.csv" %>% 
#   readr::read_csv() %>% 
#   dplyr::arrange(`作成日`) %>% 
#   dplyr::filter(`トラッカー` == "Defect") %>% 
#   dplyr::top_n(1000) %>% 
#   readr::write_csv("./redmine_data_utf8.csv")

# バグチケットの日付の範囲を取得する
tickets_date <- "./redmine_data_utf8.csv" %>% 
  readr::read_csv() %>% 
  dplyr::select(ID = '#', Tracker = 'トラッカー', Status = 'ステータス',
                OpenDateTime = '作成日', CloseDateTime = '終了日') %>% 
  dplyr::filter(Tracker == "Defect") %>% 
  dplyr::mutate(Date = lubridate::as_date(OpenDateTime)) %>% 
  dplyr::select(Date) %>% 
  dplyr::summarise(min = min(Date), max = max(Date))

# 日付の範囲のデータフレームを作成する
df_date <- seq(from = tickets_date$min, to = tickets_date$max, by = 1) %>% 
  tibble::as.tibble() %>% 
  dplyr::rename(Date = value)

# チケットオープンの日毎に集計し累計値を算出する
df_open <- "./redmine_data_utf8.csv" %>% 
  readr::read_csv() %>% 
  dplyr::select(ID = '#', Tracker = 'トラッカー', Status = 'ステータス',
                OpenDateTime = '作成日', CloseDateTime = '終了日') %>% 
  dplyr::filter(Tracker == "Defect") %>% 
  dplyr::mutate(Date = lubridate::as_date(OpenDateTime)) %>% 
  dplyr::count(Date) %>% 
  dplyr::right_join(df_date) %>% 
  dplyr::mutate_at(vars(-Date), funs(replace(., is.na(.), 0))) %>% 
  dplyr::mutate(cum = cumsum(n)) %>% 
  dplyr::rename(open_n = n, open_cum = cum)

# チケットクローズの日毎に集計し累計値を算出する
df_close <- "./redmine_data_utf8.csv" %>% 
  readr::read_csv() %>% 
  dplyr::select(ID = '#', Tracker = 'トラッカー', Status = 'ステータス',
                OpenDateTime = '作成日', CloseDateTime = '終了日') %>% 
  dplyr::filter(Tracker == "Defect" & Status == "Closed") %>%
  dplyr::mutate(Date = lubridate::as_date(CloseDateTime)) %>% 
  dplyr::count(Date) %>% 
  dplyr::right_join(df_date) %>% 
  dplyr::mutate_at(vars(-Date), funs(replace(., is.na(.), 0))) %>% 
  dplyr::mutate(cum = cumsum(n)) %>% 
  dplyr::rename(close_n = n, close_cum = cum)

df_date %>% 
  dplyr::left_join(df_open, by = "Date") %>% 
  dplyr::left_join(df_close, by = "Date") %>% 
  ggplot2::ggplot(aes(x = Date)) +
    ggplot2::geom_line(ggplot2::aes(y = open_cum), colour = "red") + 
    ggplot2::geom_line(ggplot2::aes(y = close_cum), colour = "blue") +
    ggplot2::labs(x = "日付", y = "チケット累計")
```

## ヒント
やりたいこと           | 利用する関数例                          | 備考
-----------------------|-----------------------------------------|---
最大値・最小値を求める | **`min()`**, **`max()`**, **`range()`** | 
日付に変換する         | **`lubridate::as_date()`**              | 
度数をカウントする     | **`dplyr::count()`**                    |
累計を求める           | **`cumsum()`**                          | 
置き換える             | **`replace()`**                         | 
NAか調べる             | **`is.na()`**                           |
データフレームを結合する | **`dplyr::left/right_join()`**        |

---

CC BY-NC-SA 4.0, Sampo Suzuki