<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>第2章 演習解答例</title>

<script src="site_libs/jquery-1.12.4/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-1.1/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>
<script src="site_libs/htmlwidgets-0.8/htmlwidgets.js"></script>
<script src="site_libs/datatables-binding-0.2/datatables.js"></script>
<link href="site_libs/dt-core-bootstrap-1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="site_libs/dt-core-bootstrap-1.10.12/css/dataTables.bootstrap.extra.css" rel="stylesheet" />
<script src="site_libs/dt-core-bootstrap-1.10.12/js/jquery.dataTables.min.js"></script>
<script src="site_libs/dt-core-bootstrap-1.10.12/js/dataTables.bootstrap.min.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">ソフトウェアメトリクス統計分析入門</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    例題
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./example_1.html">第1章 例題解答例</a>
    </li>
    <li>
      <a href="./example_2.html">第2章 例題解答例</a>
    </li>
    <li>
      <a href="./example_3.html">第3章 例題解答例</a>
    </li>
    <li>
      <a href="./example_4.html">第4章 例題解答例</a>
    </li>
    <li>
      <a href="./example_5.html">第5章 例題解答例</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    演習
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./exercise_1.html">第1章 演習解答例</a>
    </li>
    <li>
      <a href="./exercise_2.html">第2章 演習解答例</a>
    </li>
    <li>
      <a href="./exercise_3.html">第3章 演習解答例</a>
    </li>
    <li>
      <a href="./exercise_4.html">第4章 演習解答例</a>
    </li>
    <li>
      <a href="./exercise_5.html">第5章 演習解答例</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    その他
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./about.html">R環境情報</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Model/Infer
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../../index.html">
        <span class="fa fa-home"></span>
         
        Model/Infer Top
      </a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="../../stats/index.html">
        <span class="fa fa-bar-chart"></span>
         
        統計
      </a>
    </li>
    <li>
      <a href="../../books/index.html">
        <span class="fa fa-book"></span>
         
        書籍
      </a>
    </li>
    <li>
      <a href="../../gacco/index.html">
        <span class="fa fa-graduation-cap"></span>
         
        gacco
      </a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-github"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../../../">
        <span class="fa fa-github"></span>
         
        Cabinet
      </a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="../../../import/">　Import</a>
    </li>
    <li>
      <a href="../../../tidy/">　Tidy/Transform</a>
    </li>
    <li>
      <a href="../../index.html">
        <span class="fa fa-home"></span>
         
        Model/Infer
      </a>
    </li>
    <li>
      <a href="../../visualize/">　Visualize</a>
    </li>
    <li>
      <a href="../../communicate/">　Communicate/Automate</a>
    </li>
    <li>
      <a href="../../program/">　Program</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="https://sites.google.com/site/kantometrics/home">
        <span class="fa fa-google"></span>
         
        データ分析勉強会
      </a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">第2章 演習解答例</h1>

</div>


<!-- Include Common Links -->
<!-- SQiP -->
<!-- Books -->
<!-- Creative Commons -->
<!-- R -->
<!-- RStudio -->
<!-- Cabinet Pages -->
<div id="はじめに" class="section level1">
<h1>はじめに</h1>
<p>本資料は『<a href="http://www.juse-p.co.jp/cgi-bin/html.pl5?i=ISBN978-4-8171-9558-6" title="ソフトウェアメトリクス統計分析入門">ソフトウェアメトリクス統計分析入門</a>』(以降、テキストと記載)の第2章の演習問題を<a href="https://www.r-project.org/" title="The R Project">R</a>で解いた際の解答例を示したものです。また、<a href="http://rmarkdown.rstudio.com/" title="R Markdown form RStudio">R Markdown</a>を使うメリットを示すための一手段として作成していますので、テキストにおける計算方法とは異なる部分もあります。本資料で使用しているデータの入手に関してはテキストにてご確認下さい。<br />
本資料がHTML形式の場合、Rのコードを参照するには右側にある<strong><code>[Code]</code></strong>ボタンをクリックして下さい。なお、JavaScriptは必ずOnにしてご覧下さい。</p>
</div>
<div id="演習問題" class="section level1">
<h1>演習問題</h1>
<blockquote>
<p>第2章は全ての演習問題でダウンロードファイル内の「第2章_例題演習データ」ファイルの各シートにある演習データを使用します。</p>
</blockquote>
</div>
<div id="演習-2.1" class="section level1">
<h1>演習 2.1</h1>
<blockquote>
<p>あるアウトソース先から100個のモジュールが納品されました。納品されたモジュールの品質を確認するために10個のモジュールをサンプリングして受入確認テストを実施しました。 その結果、各モジュールの欠陥密度は以下のとおりでした。</p>
<p>欠陥密度： 2.8, 5.2, 5.3, 4.7, 4.8, 5.8, 4.0, 2.2, 2.1, 3.5</p>
<p>この組織ではプロジェクトトータルの欠陥密度の標準値が3.0 となっており、今回納品されたモジュール全体の平均がその組織標準を超えていそうならば受入はせず、品質を高めてから再納品してもらうことを考えています。 そのためにはアウトソース先にも納得できる形で、判断の根拠を示す必要があります。受入の許可か拒否か、どちらが妥当な判断といえるでしょうか。</p>
</blockquote>
<div id="データの設定" class="section level2">
<h2>データの設定</h2>
<p>本演習で利用するデータの数は多くなので、直接、Rのコードで変数として設定します。</p>
<pre class="r"><code>ref &lt;- c(3.0)                                               # 標準値
dd &lt;- c(2.8, 5.2, 5.3, 4.7, 4.8, 5.8, 4.0, 2.2, 2.1, 3.5)   # 欠陥密度</code></pre>
</div>
<div id="検定" class="section level2">
<h2>検定</h2>
<p>固定的な基準値に対してサンプリングデータの平均値に差があるかどうかを確認しますので、例題2.2と同じ1標本t検定を用います。対立仮説（帰無仮説）については省略。</p>
<pre class="r"><code># 返り値をinline chunkで利用するために一度、変数に代入する
result.t.test &lt;- t.test(dd, alternative = &quot;less&quot;, mu = ref)
result.t.test</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  dd
## t = 2.4647, df = 9, p-value = 0.9821
## alternative hypothesis: true mean is less than 3
## 95 percent confidence interval:
##      -Inf 4.813488
## sample estimates:
## mean of x 
##      4.04</code></pre>
<p>検定の結果<span class="math inline">\(p = 0.9820604\)</span>、95%信頼区間は(<span class="math inline">\(-\infty{}, 4.8134877\)</span>)となり、帰無仮説は棄却されませんでしたので、基準値より納入されたモジュールの欠陥密度の平均値が小さいとは言えず、受入れは基準に達して いるとは言いがたく、受入れ拒否とみなせます。</p>
</div>
</div>
<div id="演習-2.2" class="section level1">
<h1>演習 2.2</h1>
<blockquote>
<p>テスト技法の改善を行いました。実験として5つのモジュールに対して、新旧2つの技法を用いてテストを行い、以下の欠陥密度のデータを得ました。 新技法は欠陥検出能力が向上したといえるでしょうか。</p>
</blockquote>
<div id="データの設定-1" class="section level2">
<h2>データの設定</h2>
<p>本演習で利用するデータは予めCSVファイルとして保存されているものとします。</p>
</div>
<div id="データの確認" class="section level2">
<h2>データの確認</h2>
<pre class="r"><code>x.stacked &lt;- stack(x)
stripchart(values ~ ind, data = x.stacked)</code></pre>
<p><img src="exercise_2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="検定-1" class="section level2">
<h2>検定</h2>
<pre class="r"><code># 返り値をinline chunkで利用するために一度、変数に代入する
result.t.test &lt;- t.test(x$new, x$old, alternative = &quot;greater&quot;, paired=TRUE)
result.t.test &lt;- t.test(values ~ ind, data = x.stacked, alternative = &quot;greater&quot;, paired=TRUE)
result.t.test</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  values by ind
## t = 2.7386, df = 4, p-value = 0.02599
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  0.06646789        Inf
## sample estimates:
## mean of the differences 
##                     0.3</code></pre>
<p>検定の結果<span class="math inline">\(p = 0.0259898\)</span>、95%信頼区間は<span class="math inline">\((0.0664679, \infty{})\)</span>となり、帰無仮説は棄却されましたので、平均値の差に 有意差があり、新技法は欠陥検出能力が向上しているといえます。</p>
</div>
</div>
<div id="演習-2.3" class="section level1">
<h1>演習 2.3</h1>
<blockquote>
<p>開発時の品質状況を示すメトリクスとリリース後の品質問題の有無の関連性を示すために、リリースして1年以上経過したプロジェクトを品質問題の有無の2つに分けて、それぞれの開発終了時のシステムテストでの欠陥密度のデータを比較することにしました。 得られたデータは以下のとおりです。システムテストでの欠陥密度とリリース後の品質問題の有無の関連性はあるといえるでしょうか。</p>
</blockquote>
<div id="データの設定-2" class="section level2">
<h2>データの設定</h2>
<p>本演習で利用するデータは予めCSVファイルとして保存されているものとします。</p>
</div>
<div id="データの変換" class="section level2">
<h2>データの変換</h2>
<p>本演習のデータは、「欠陥あり」と「欠陥なし」は異なるプロジェクトであることから独立サンプルt検定<code>t.test {stats}</code>にて有意差を確認します。 読み込んだデータは2変数のデータフレームになっていますので、独立サンプルt検定を行うために以下のように1変数と因子の形に変換しておきます。</p>
<pre class="r"><code>x.stacked &lt;- stack(x)
# 念の為にNAを含むデータを外す
x.stacked &lt;- na.omit(x.stacked)

df_print(x)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">yes</th>
<th align="right">no</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">4.5</td>
<td align="right">2.7</td>
</tr>
<tr class="even">
<td align="right">2.0</td>
<td align="right">1.2</td>
</tr>
<tr class="odd">
<td align="right">4.5</td>
<td align="right">2.3</td>
</tr>
<tr class="even">
<td align="right">3.2</td>
<td align="right">1.8</td>
</tr>
<tr class="odd">
<td align="right">4.2</td>
<td align="right">3.0</td>
</tr>
<tr class="even">
<td align="right">NA</td>
<td align="right">4.0</td>
</tr>
</tbody>
</table>
</div>
<div id="データの確認-1" class="section level2">
<h2>データの確認</h2>
<pre class="r"><code>stripchart(values ~ ind, data = x.stacked)</code></pre>
<p><img src="exercise_2_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="検定-2" class="section level2">
<h2>検定</h2>
<p>変換したデータを用いて、その分布を確認し等分散か否かをF検定<code>var.test {stats}</code>で確認します。</p>
<pre class="r"><code># var.test(x$yes, x$no, alternative = &quot;less&quot;)
var.test(x$yes, x$no, alternative = &quot;two.sided&quot;)</code></pre>
<pre><code>## 
##  F test to compare two variances
## 
## data:  x$yes and x$no
## F = 1.2258, num df = 4, denom df = 5, p-value = 0.8106
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##   0.1659257 11.4793461
## sample estimates:
## ratio of variances 
##            1.22584</code></pre>
<p>F検定の結果、帰無仮説は棄却されなかったので、2つのデータは等分散とは言えないのでWelchのt検定<code>t.test {stats}</code>を用います。</p>
<pre class="r"><code># 返り値をinline chunkで利用するために一度、変数に代入する
result.t.test &lt;- t.test(values ~ ind, alternative = &quot;two.sided&quot;,
                        var.equal = FALSE, data = x.stacked)
result.t.test</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  values by ind
## t = -1.8845, df = 8.2404, p-value = 0.09516
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.6166094  0.2566094
## sample estimates:
##  mean in group no mean in group yes 
##              2.50              3.68</code></pre>
<p>検定の結果<span class="math inline">\(p = 0.0951584\)</span>、95%信頼区間は<span class="math inline">\((-2.6166094, 0.2566094)\)</span>となり、帰無仮説は棄却されませんしたので、平均値の差に有意差があるとは言えず、システムテストでの欠陥密度とリリース後の品質問題の有無の「関連性はある」とも言えません。</p>
</div>
</div>
<div id="演習-2.4" class="section level1">
<h1>演習 2.4</h1>
<blockquote>
<p>ベースとなるシステムに改良を加えました。そして。改良システムのユーザビリティテストを行い、ベースシステムとの比較で以下の5段階評価を行いました。</p>
<p>　1：非常に使いづらい<br />
　2：使いづらい<br />
　3：あまり変わらない<br />
　4：使いやすい<br />
　5：非常に使いやすい</p>
<p>被験者10名のそれぞれの評点は以下のとおりです。改良システムはベースシステムに比べて使いやすくなったといえるでしょうか。</p>
</blockquote>
<div id="データの設定-3" class="section level2">
<h2>データの設定</h2>
<p>本演習で利用するデータは予めCSVファイルとして保存されているものとします。</p>
</div>
<div id="検定-3" class="section level2">
<h2>検定</h2>
<p>演習2.2と同じで固定的な基準値(3:あまり変わらない)に対するアンケート結果の平均の差があるかどうかを見ることから「1標本t検定」を用います。Rで1標本t検定を行う場合、<code>t.test {stats}</code>を使い、対立仮説（帰無仮説）は基準値(<span class="math inline">\(\mu_0\)</span>)に対するアンケートの平均値(<span class="math inline">\(\mu\)</span>)として以下の3通りが考えられます。</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\mu \neq \mu_0\)</span> （帰無仮説 <span class="math inline">\(\mu = \mu_0\)</span>）</li>
<li><span class="math inline">\(\mu &lt; \mu_0\)</span> （帰無仮説 <span class="math inline">\(\mu \geq \mu_0\)</span>）</li>
<li><span class="math inline">\(\mu &gt; \mu_0\)</span> （帰無仮説 <span class="math inline">\(\mu \leq \mu_0\)</span>）</li>
</ol>
<p>設問として「使いやすくなったと言えるか？」なので、アンケートの5段階評価の平均値が<span class="math inline">\(\mu &gt; \mu_0\)</span>（帰無仮説 <span class="math inline">\(\mu \leq \mu_0\)</span>）となるかを検定します。</p>
<pre class="r"><code># 返り値をinline chunkで利用するために一度、変数に代入する
result.t.test &lt;- t.test(x$evaluation, alternative = &quot;greater&quot;, mu = 3.0)
result.t.test</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  x$evaluation
## t = 2.3333, df = 9, p-value = 0.02225
## alternative hypothesis: true mean is greater than 3
## 95 percent confidence interval:
##  3.150066      Inf
## sample estimates:
## mean of x 
##       3.7</code></pre>
<p>検定の結果p値は<span class="math inline">\(p = 0.0222518\)</span>であり帰無仮説は棄却され、平均値は<span class="math inline">\(\mu = 3.7\)</span>、95%信頼区間は<span class="math inline">\((3.1500661, \infty{})\)</span>であることから改良システムは使いやすくなったと言えます。</p>
</div>
</div>
<div id="演習-2.5" class="section level1">
<h1>演習 2.5</h1>
<blockquote>
<p>図2.16 に4 パターンのA とB の2 群データを示します。 いずれのパターンも平均はA群が1.2でB群が1.0 なっており、 平均の差は0.2で統一されています。 また、A群とB群のデータ数と標準偏差（n－1で割ったもの）の値も同じです。 グラフはA群とB群のデータ分布の違いを可視化しています。4つのパターンの違いは表2.5のとおりです。</p>
<p>(表2.5 4パターンのデータセットの各種指標の違い)</p>
<table>
<thead>
<tr class="header">
<th>パターン</th>
<th>平均値の差</th>
<th>データ数</th>
<th>標準偏差</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>パターン1</td>
<td>0.2</td>
<td>9</td>
<td>0.27</td>
</tr>
<tr class="even">
<td>パターン2</td>
<td>0.2</td>
<td>9</td>
<td>0.14</td>
</tr>
<tr class="odd">
<td>パターン3</td>
<td>0.2</td>
<td>18</td>
<td>0.27</td>
</tr>
<tr class="even">
<td>パターン4</td>
<td>0.2</td>
<td>4</td>
<td>0.14</td>
</tr>
</tbody>
</table>
<p>これらの数値を使えばt値およびp値を算出して有意差の違いを確認できますが、まずは図2.16のグラフだけを見て、パターン1と比較して、パターン2～4のp値の大きさの違いを予想してみてください。 そしてその後それぞれのパターンの検定結果のp値を算出して、予想が合っていたかを確認してください．</p>
<div class="figure">
<img src="./data/ex2_5_fig.jpg" alt="図2.16" />
<p class="caption">図2.16</p>
</div>
</blockquote>
<div id="データの設定-4" class="section level2">
<h2>データの設定</h2>
<p>本演習で利用するデータは予めCSVファイルとして保存されているものとします。</p>
</div>
<div id="データの確認-2" class="section level2">
<h2>データの確認</h2>
<pre class="r"><code># stripchart(data.1 ~ group.1, xlim = c(0, 2), data = na.omit(x[1:2]))
# stripchart(data.2 ~ group.2, xlim = c(0, 2), data = na.omit(x[3:4]))
# stripchart(data.3 ~ group.3, xlim = c(0, 2), data = na.omit(x[5:6]))
# stripchart(data.4 ~ group.4, xlim = c(0, 2), data = na.omit(x[7:8]))

# NAを削除するためにna.omit {stats}、NULL因子を削除するためにdroplevels {base}を
# 用います
stripchart(data ~ group, xlim = c(0, 2), data = droplevels(na.omit(x[1:2])),
           main = &quot;Pattern A&quot;)</code></pre>
<p><img src="exercise_2_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code>with(droplevels(na.omit(x[1:2])), tapply(data, INDEX = group, FUN = mean))</code></pre>
<pre><code>##   A   B 
## 1.0 1.2</code></pre>
<pre class="r"><code>with(droplevels(na.omit(x[1:2])), tapply(data, INDEX = group, FUN = sd))</code></pre>
<pre><code>##         A         B 
## 0.2738613 0.2738613</code></pre>
<pre class="r"><code>stripchart(data ~ group, xlim = c(0, 2), data = droplevels(na.omit(x[3:4])),
           main = &quot;Pattern B&quot;)</code></pre>
<p><img src="exercise_2_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
<pre class="r"><code>with(droplevels(na.omit(x[3:4])), tapply(data, INDEX = group, FUN = mean))</code></pre>
<pre><code>##   A   B 
## 1.0 1.2</code></pre>
<pre class="r"><code>with(droplevels(na.omit(x[3:4])), tapply(data, INDEX = group, FUN = sd))</code></pre>
<pre><code>##         A         B 
## 0.1369306 0.1369306</code></pre>
<pre class="r"><code>stripchart(data ~ group, xlim = c(0, 2), data = droplevels(na.omit(x[5:6])),
           main = &quot;Pattern C&quot;)</code></pre>
<p><img src="exercise_2_files/figure-html/unnamed-chunk-14-3.png" width="672" /></p>
<pre class="r"><code>with(droplevels(na.omit(x[5:6])), tapply(data, INDEX = group, FUN = mean))</code></pre>
<pre><code>##        A        B 
## 1.003889 1.203889</code></pre>
<pre class="r"><code>with(droplevels(na.omit(x[5:6])), tapply(data, INDEX = group, FUN = sd))</code></pre>
<pre><code>##         A         B 
## 0.2654882 0.2654882</code></pre>
<pre class="r"><code>stripchart(data ~ group, xlim = c(0, 2), data = droplevels(na.omit(x[7:8])),
           main = &quot;Pattern D&quot;)</code></pre>
<p><img src="exercise_2_files/figure-html/unnamed-chunk-14-4.png" width="672" /></p>
<pre class="r"><code>with(droplevels(na.omit(x[7:8])), tapply(data, INDEX = group, FUN = mean))</code></pre>
<pre><code>##   A   B 
## 1.0 1.2</code></pre>
<pre class="r"><code>with(droplevels(na.omit(x[7:8])), tapply(data, INDEX = group, FUN = sd))</code></pre>
<pre><code>##         A         B 
## 0.1351542 0.1351542</code></pre>
</div>
</div>
<div id="おまけ" class="section level1">
<h1>おまけ</h1>
<div id="t.test-statsでのt検定" class="section level2">
<h2>t.test {stats}でのt検定</h2>
<p><code>t.test {stats}</code>関数は、引数の指定により様々なt検定を行えます。そこで、t検定の種類と<code>t.test {stats}</code>での計算方法を整理しておきます。</p>
<table>
<thead>
<tr class="header">
<th>標本</th>
<th>関係</th>
<th>分散</th>
<th>指定方法</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1標本の</td>
<td>N/A</td>
<td>N/A</td>
<td>t.test(x, mu = a)</td>
</tr>
<tr class="even">
<td>2群間の</td>
<td>対応のない</td>
<td>等分散</td>
<td>t.test(x, y, var.equal = TRUE)</td>
</tr>
<tr class="odd">
<td>2群間の</td>
<td>対応のない</td>
<td>不等分散</td>
<td>t.test(x, y, var.equal = FALSE)</td>
</tr>
<tr class="even">
<td>2群間の</td>
<td>対応のある</td>
<td>N/A</td>
<td>t.test(x, y, paired = TRUE)</td>
</tr>
</tbody>
</table>
<p>なお、<code>mu</code>の既定値は<code>0</code>。<code>var.equal</code>、<code>paired</code>の既定値は共に<code>FALSE</code>です。</p>
<p>2群間の検定については、<code>formula</code>形式を用いた指定も可能で、データフレーム<code>x</code>において数値<code>value</code>、層別変数<code>factor</code>にデータが格納されているとした場合、以下のように指定します。</p>
<pre><code># 2群間の対応のない（等分散） - 独立サンプルt検定はこの計算式@Rcmdr
t.test(value ~ factor, data = x, var.equal = TURE)

# 2群間の対応のない（不等分散） - 独立サンプルt検定はこの計算式@Rcmdr
t.test(value ~ factor, data = x, var.equal = FALSE)

# 2群間の対応のある - 対応のあるt検定はこの計算式を使わない@Rcmdr
t.test(value ~ factor, data = x, paired = TURE)</code></pre>
<p><code>factor</code>は因子名でソートされた順で評価されますので、順番に注意して下さい。</p>
<!--
 TeXで「~」を表記する場合は、\verb|~|とする。その他の特殊文字は以下を参照
 \textasciitildeや\textasciicircumは使えない
 http://www.rsch.tuis.ac.jp/~mizutani/online/latex/specialchar.html
 http://www.latex-cmd.com/struct/verb.html
-->
</div>
<div id="t.test-statsでの対立仮説指定方法" class="section level2">
<h2>t.test {stats}での対立仮説指定方法</h2>
<div id="標本の場合" class="section level3">
<h3>１標本の場合</h3>
<p>対立仮説<code>alternative hypothesis</code>の指定（引数<code>alternative</code>）は1標本の場合、</p>
<pre><code>t.test(x, mu = mu0, alternative = &quot;option&quot;)</code></pre>
<p>と指定し、平均<span class="math inline">\(\mu\)</span>と基準値(比較値)<span class="math inline">\(\mu_0\)</span>に対して下表のようになります。</p>
<table>
<thead>
<tr class="header">
<th>対立仮説 （帰無仮説）</th>
<th>指定方法</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mu \neq \mu_0\)</span> （<span class="math inline">\(\mu = \mu_0\)</span>）</td>
<td>alternative = “two.sided”</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu &lt; \mu_0\)</span> （<span class="math inline">\(\mu \geq \mu_0\)</span>）</td>
<td>alternative = “less”</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu &gt; \mu_0\)</span> （<span class="math inline">\(\mu \leq \mu_0\)</span>）</td>
<td>alternative = “greater”</td>
</tr>
</tbody>
</table>
<p><img src="image/1標本.jpg" /><br />
1標本t検定</p>
</div>
<div id="群間の場合" class="section level3">
<h3>２群間の場合</h3>
<p>対応のある2群間の場合は、以下のように指定し</p>
<pre><code>t.test(x, y, alternative = &quot;option&quot;, ...)</code></pre>
<p>対立仮説の指定(引数<code>alternative</code>)は平均の差（<span class="math inline">\(\delta = \mu_x - \mu_y\)</span>）に対して下表のようになります。</p>
<table>
<thead>
<tr class="header">
<th>対立仮説 （帰無仮説）</th>
<th>指定方法</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\delta \neq 0\)</span> （<span class="math inline">\(\delta = 0\)</span>）</td>
<td>alternative = “two.sided”</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\delta &lt; 0\)</span> （<span class="math inline">\(\delta \geq 0\)</span>）</td>
<td>alternative = “less”</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\delta &gt; 0\)</span> （<span class="math inline">\(\delta \leq 0\)</span>）</td>
<td>alternative = “greater”</td>
</tr>
</tbody>
</table>
<p><img src="image/2標本_対応のある.jpg" /><br />
対応のあるt検定</p>
<p>　<br />
対応のない2群間の場合は同様の指定で、平均の差（<span class="math inline">\(\delta = \mu_x - \mu_y\)</span>）で考える場合は上表のように平均値<span class="math inline">\(\mu_x\)</span>, <span class="math inline">\(\mu_y\)</span>に対して考える場合は下表のようになります。</p>
<table>
<thead>
<tr class="header">
<th>対立仮説 （帰無仮説）</th>
<th>指定方法</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mu_x \neq \mu_y\)</span> （<span class="math inline">\(\mu_x = \mu_y\)</span>）</td>
<td>alternative = “two.sided”</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu_x &lt; \mu_y\)</span> （<span class="math inline">\(\mu_x \geq \mu_y\)</span>）</td>
<td>alternative = “less”</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu_x &gt; \mu_y\)</span> （<span class="math inline">\(\mu_x \leq \mu_y\)</span>）</td>
<td>alternative = “greater”</td>
</tr>
</tbody>
</table>
<p><img src="image/2標本_対応のない.jpg" /><br />
独立サンプルt検定<br />
　<br />
<code>formula</code>形式で指定した場合は、因子順にx, yと読み替えて下さい。また、他のオプションについてはヘルプで確認して下さい。</p>
<!-- ## t.test {stats}を使わない方法 -->
<!-- Excel使った場合と同じ方法（テキストの方法）で1標本t検定を解いてみます。 -->
<!-- ```{r} -->
<!-- x.omit <- droplevels(na.omit(x[1:2])) -->
<!-- # データ数 -->
<!-- n <- tapply(x.omit$data, INDEX = x.omit$group, FUN = length) -->
<!-- # 自由度 = データ数 - 1 -->
<!-- f <- n - 1 -->
<!-- # 平均値 -->
<!-- m <- tapply(x.omit$data, INDEX = x.omit$group, FUN = mean) -->
<!-- # 標準偏差 -->
<!-- s <- tapply(x.omit$data, INDEX = x.omit$group, FUN = sd) -->
<!-- # t分布の標準偏差 -->
<!-- # t値 -->
<!-- # p値 -->
<!-- x.omit <- droplevels(na.omit(x[3:4])) -->
<!-- n <- tapply(x.omit$data, INDEX = x.omit$group, FUN = length) -->
<!-- x.omit <- droplevels(na.omit(x[5:6])) -->
<!-- n <- tapply(x.omit$data, INDEX = x.omit$group, FUN = length) -->
<!-- x.omit <- droplevels(na.omit(x[7:8])) -->
<!-- n <- tapply(x.omit$data, INDEX = x.omit$group, FUN = length) -->
<!-- ``` -->
<hr />
<!-- Include Footer -->
<p><img src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" title="CC BY-NC-SA 4.0 icon" alt="Sampo Suzuki" /> <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/deed.ja" title="CC BY-NC-SA 4.0">CC BY-NC-SA 4.0</a>, Sampo Suzuki [2017-04-22 14:23(JST)]</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
