---
title: "第1章 練習問題回答例"
output: 
  html_document:  
    number_section: no
---

<!-- Include Common Links -->
```{r exercies_1, child="../../../common/links.Rmd"}
```

```{r setup, include=FALSE}
# 共通chunkオプションの指定
knitr::opts_chunk$set(warning = FALSE, echo = TRUE)

# データハンドリングで利用する外部パッケージの読み込み
require(tidyverse)
# 表示で利用する外部パッケージの読み込み
require(gridExtra)
require(DT)
require(knitr)
tidyverse::tidyverse_conflicts()

# ローカル定義関数の読み込み
source("../../../common/common.R")
```

# はじめに {.unnumbered}
本資料は『[改訂版 日本統計学会公式認定 統計検定2級対応　統計学基礎](http://www.tokyo-tosho.co.jp/books/978-4-489-02227-2/)』（以降、テキスト）の練習問題をRを用いて紐解いていく際の例を示したものです。したがいまして、設問についてはテキストにてご確認ください。また、本資料で使用しているデータの入手に関してもテキストにてご確認ください。

## 本資料について
本資料は[R Markdown][RM]ならびに[tidyverse][tidy]パッケージの有用性を示すための一手段として作成していますのでテキストにおけるグラフ表現や計算方法と異なる部分があります。

## Rのコードについて
[R][R]のコードはデフォルトで非表示設定になっています。[R][R]のコードを参照する場合はページ右側に表示される[Code]ボタンをクリックして下さい。なお、ブラウザのJavaScriptが有効になっていない場合はコードを見ることが出来ませんので必ずJavaScriptを有効に設定して下さい。
　  

# 問 1.1
```{r}
x <- read.csv(file = "./data/1章/練習問題/weather.csv", fileEncoding = "CP932")

x %>% 
  df_print(caption = "1月の東京における気象データ")
```
　  

## 解(1)
```{r}
data.frame(質的変数 = c("風向き", "", ""),
           量的変数 = c("平均気温", "平均湿度", "日照時間")) %>% 
  knitr::kable()
```
　  

## 解(2)
累積相対度数が最終的に1.0になっていないのは丸め誤差のためです。
```{r}
x %>% 
  dplyr::select(temp = 平均気温) %>% 
  dplyr::mutate(breaks = cut(temp, pretty(range(temp),
                                          n = nclass.Sturges(temp)))) %>% 
  dplyr::count(breaks) %>% 
  dplyr::mutate(cum = cumsum(n), rel = round(n/sum(n), 2),
                cum_rel = cumsum(rel)) %>% 
  dplyr::rename('階級' = breaks, '度数' = n, '累積度数' = cum, '相対度数' = rel, 
                '累積相対度数' = cum_rel) %>% 
  knitr::kable(caption = "平均気温の度数分布表")

breaks <- pretty(range(x$平均気温), n = nclass.Sturges(x$平均気温))
x %>% 
  dplyr::select(temp = 平均気温) %>% 
  ggplot2::ggplot(aes(x = temp)) +
    ggplot2::geom_histogram(breaks = breaks, closed = "right") +
    ggplot2::xlab("平均気温") + ggplot2::ylab("度数") +
    ggplot2::ggtitle("平均気温のヒストグラム",
                     subtitle = paste("階級幅 = ", diff(breaks), "度", sep = ""))
```
　  

## 解(3)
```{r}
# 平均値、標本分散、標準偏差を2桁に丸める関数
r_mean <- function(x){round(mean(x), 2)}
s_var <- function(x){
  n <- length(x)
  round(((n - 1)/n)*var(x), 2)
}
r_sd <- function(x){round(sd(x), 2)}

x %>% 
  dplyr::select(temp = 平均気温, hum = 平均湿度, shine = 日照時間) %>% 
  dplyr::summarise_each(funs = funs(r_mean, s_var, r_sd)) %>%
  dplyr::select('平均気温の平均値' = temp_r_mean,
                '平均気温の分散' = temp_s_var,
                '平均気温の標準偏差' = temp_r_sd,
                '平均湿度の平均値' = hum_r_mean,
                '平均湿度の分散' = hum_s_var,
                '平均湿度の標準偏差' = hum_r_sd,
                '日照時間の平均値' = shine_r_mean,
                '日照時間の分散' = shine_s_var,
                '日照時間の標準偏差' = shine_r_sd) %>% 
  t() %>%  as.data.frame() %>% knitr::kable()
```
　  

## 解(4)
累積相対度数が最終的に1.0になっていないのは丸め誤差のためです。
```{r}
x %>% 
  dplyr::select(temp = 平均気温) %>% 
  dplyr::mutate(breaks = cut(temp, pretty(range(temp),
                                          n = nclass.Sturges(temp)))) %>% 
  dplyr::count(breaks) %>% 
  dplyr::mutate(cum = cumsum(n), rel = round(n/sum(n), 2),
                cum_rel = cumsum(rel)) %>% 
  dplyr::rename('階級' = breaks, '度数' = n, '累積度数' = cum, '相対度数' = rel, 
                '累積相対度数' = cum_rel) %>% 
  knitr::kable(caption = "平均気温の度数分布表")

x %>% 
  ggplot2::ggplot(aes(平均気温)) +
    ggplot2::stat_ecdf() +
    ggplot2::ylab("累積相対度数") +
    ggplot2::ggtitle("平均気温の累積分布図")
```
　  

## 解(5)
```{r}
x %>% 
  dplyr::count(風向き) %>% 
  knitr::kable()

x %>% 
  ggplot2::ggplot(aes(x = 風向き, fill = 風向き, alpha = 0.5)) +
    ggplot2::geom_bar() +
    ggplot2::theme(legend.position = "none")

x %>% 
  dplyr::count(風向き) %>% 
  ggplot2::ggplot(aes(x = "", y = n, fill = 風向き)) +
    ggplot2::geom_bar(width = 1, stat = "identity", alpha = 0.5) +
    ggplot2::coord_polar("y", direction = 1) +
    ggplot2::xlab("") + ylab("")
```
　  

## 解(6)
```{r}
fivenum(x$平均気温)

x %>% 
  dplyr::select(temp = 平均気温) %>% 
  ggplot2::ggplot(aes(x = 0, y = temp)) +
    ggplot2::geom_boxplot() +
    ggplot2::xlab("") + ggplot2::ylab("平均気温") +
    ggplot2::ggtitle("平均気温の箱ひげ図")
```
　  

## 解(7)
```{r}
# 平均気温-平均湿度
x %>% 
  dplyr::select(x = 平均気温, y = 平均湿度, wind = 風向き) %>% 
  ggplot2::ggplot(aes(x, y, colour = wind, shape = wind)) +
    ggplot2::geom_point(size = 2.5) +
    ggplot2::xlab("平均気温") + ggplot2::ylab("平均湿度") +
    ggplot2::ggtitle("平均気温と平均湿度の散布図")

# 平均気温-日照時間
x %>% 
  dplyr::select(x = 平均気温, y = 日照時間, wind = 風向き) %>% 
  ggplot2::ggplot(aes(x, y, colour = wind, shape = wind)) +
    ggplot2::geom_point(size = 2.5) +
    ggplot2::xlab("平均気温") + ggplot2::ylab("日照時間") +
    ggplot2::ggtitle("平均気温と日照時間の散布図")

# 平均湿度-日照時間
x %>% 
  dplyr::select(x = 平均湿度, y = 日照時間, wind = 風向き) %>% 
  ggplot2::ggplot(aes(x, y, colour = wind, shape = wind)) +
    ggplot2::geom_point(size = 2.5) +
    ggplot2::xlab("平均湿度") + ggplot2::ylab("日照時間") +
    ggplot2::ggtitle("平均湿度と日照時間の散布図")

# 無相関の検定
cor_1 <- with(x, cor.test(平均気温, 平均湿度))
cor_2 <- with(x, cor.test(平均気温, 日照時間))
cor_3 <- with(x, cor.test(平均湿度, 日照時間))

data.frame(name = c(cor_1$data.name, cor_2$data.name, cor_3$data.name),
           cor = c(cor_1$estimate, cor_2$estimate, cor_3$estimate),
           p = c(cor_1$p.value, cor_2$p.value, cor_3$p.value)) %>% 
  dplyr::mutate(cor = round(cor, 2), p = round(p, 3),
                result = ifelse(p < 0.05, "棄却される", "棄却されない")) %>% 
  dplyr::rename('変数' = name, '相関係数' = cor, 'p値' = p,
                '帰無仮説' = result) %>% 
  knitr::kable(caption = "無相関の検定結果")
```
　  

## 解(8)
```{r}
x %>% 
  dplyr::select(day = 日, temp = 平均気温) %>% 
  ggplot2::ggplot(aes(x = day, y = temp)) +
    ggplot2::geom_point() +
    ggplot2::geom_line() +
    ggplot2::xlab("日") + ggplot2::ylab("気温[度]") +
    ggplot2::ggtitle("平均気温の日ごとの推移")
```
　  

# 問 1.2
```{r}
x <- read.csv(file = "./data/1章/練習問題/test.csv", fileEncoding = "CP932")

x %>% 
  df_print(caption = "2回行った試験の結果")
```
　  

## 解(1)
```{r}
r_mean <- function(x){round(mean(x), 1)}
s_var <- function(x){
  n <- length(x)
  round(((n - 1)/n)*var(x), 1)
}
r_sd <- function(x){round(sqrt(s_var(x)), 1)}

x_scale <- x %>% 
  dplyr::select(test_1 = １回目, test_2 = ２回目) %>% 
  dplyr::summarise_each(funs = funs(r_mean, r_sd))

x_scale %>% 
  dplyr::select('１回目平均点' = test_1_r_mean, '１回目標準偏差' = test_1_r_sd,
                '２回目平均点' = test_2_r_mean, '２回目標準偏差' = test_2_r_sd) %>% 
  t() %>%  as.data.frame() %>% 
  knitr::kable()
```
　  

## 解(2)
```{r}
x %>% 
  dplyr::filter(学生 == "C") %>% 
  dplyr::rowwise() %>% 
  mutate(平均値 = round(mean(c(１回目, ２回目), na.rm = TRUE), digits = 2)) %>% 
  knitr::kable()

x %>% 
  dplyr::mutate(z_1 = round(scale(１回目, center = x_scale$test_1_r_mean,
                                  scale = x_scale$test_1_r_sd), 2),
                z_2 = round(scale(２回目, center = x_scale$test_2_r_mean,
                                  scale = x_scale$test_2_r_sd), 2)) %>%
  dplyr::select(学生, '１回目Zスコア' = z_1, '２回目Zスコア' = z_2) %>% 
  df_print()

```
　  

## 解(3)
```{r}
x %>% 
  dplyr::select(１回目, ２回目) %>% 
  dplyr::summarise_each(funs(round(r_sd(.)/r_mean(.), 2))) %>% 
  knitr::kable()
```
　  

## 解(4)
```{r}
x %>% 
  dplyr::select(id = 学生, test_1 = １回目, test_2 = ２回目) %>% 
  ggplot2::ggplot(aes(x = test_1, y = test_2, colour = id, label = id)) +
    ggplot2::geom_vline(xintercept = x_scale$test_1_r_mean, linetype = "dotted") +
    ggplot2::geom_hline(yintercept = x_scale$test_2_r_mean, linetype = "dotted") +
    ggplot2::geom_point() +
    ggplot2::geom_label(nudge_x = 1.2) +
    ggplot2::xlab("１回目") + ggplot2::ylab("２回目") +
    ggplot2::ggtitle("試験１回目と２回目の得点散布図",
                     subtitle = "点線は平均点")

x %>% 
  dplyr::select(x = １回目, y = ２回目) %>% 
  with(cor.test(x, y))
```
　  

## 解(5)
```{r}
x %>% 
  dplyr::select(x = １回目, y = ２回目) %>% 
  with(lm(y ~ x))
```
　  

## 解(6)
```{r}
summary(with(x, lm(２回目 ~ １回目)))

x %>% 
  dplyr::select(id = 学生, test_1 = １回目, test_2 = ２回目) %>% 
  ggplot2::ggplot(aes(x = test_1, y = test_2)) +
    ggplot2::geom_vline(xintercept = x_scale$test_1_r_mean, linetype = "dotted") +
    ggplot2::geom_hline(yintercept = x_scale$test_2_r_mean, linetype = "dotted") +
    ggplot2::geom_point() +
    ggplot2::geom_smooth(method = "lm") +
    ggplot2::geom_label(aes(colour = id, label = id), nudge_x = 1.2) +
    ggplot2::xlab("１回目") + ggplot2::ylab("２回目") +
    ggplot2::ggtitle("試験１回目と２回目の得点散布図",
                     subtitle = "点線は平均点")
```
　  

# 問 1.3
```{r}
x <- read.csv(file = "./data/1章/練習問題/planet.csv", fileEncoding = "CP932")

x %>% 
  df_print(caption = "太陽系の惑星の軌道長半径[AU]と公転周期[年]")
```
　  

## 解(1)
```{r}
summary(with(x, lm(公転周期 ~ 軌道長半径)))

x %>% 
  dplyr::select(name = 惑星, orbital = 軌道長半径, r_cycle = 公転周期) %>% 
  ggplot2::ggplot(aes(x = orbital, y = r_cycle)) +
    ggplot2::geom_point() +
    ggplot2::geom_smooth(method = "lm") +
    ggplot2::geom_label(aes(colour = name, label = name),
                        nudge_x = 2, nudge_y = -5) +
    ggplot2::xlab("軌道長半径[AU]") + ggplot2::ylab("公転周期[年]") +
    ggplot2::ggtitle("軌道長半径と公転周期の関係")
```
　 

## 解(2)
```{r}
x %>% 
  dplyr::mutate(軌道長半径_2 = 軌道長半径 ^ 2) %>% 
  with(lm(公転周期 ~ 軌道長半径_2)) %>% 
  summary()

x %>% 
  dplyr::select(name = 惑星, orbital = 軌道長半径, r_cycle = 公転周期) %>% 
  dplyr::mutate(orbital_2 = orbital ^ 2) %>% 
  ggplot2::ggplot(aes(x = orbital_2, y = r_cycle)) +
    ggplot2::geom_point() +
    ggplot2::geom_smooth(method = "lm") +
    ggplot2::geom_label(aes(colour = name, label = name),
                        nudge_x = 65, nudge_y = 0) +
    ggplot2::xlab("軌道長半径の二乗[AU^2]") + ggplot2::ylab("公転周期[年]") +
    ggplot2::ggtitle("軌道長半径の二乗と公転周期の関係")
```

---

<!-- Include Footer -->
```{r child="../../../common/footer.Rmd"}
```