---
title: "Redmine issues in 2018"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
require(DT)
require(flexdashboard)
require(plotly)
# require(redmineR)
require(tidyverse)    # tidyverseは最後に呼び出す方がコンフリクトの影響小

# Local Function
map_if_chr <- function(.x, .f) {
  purrr::map_if(.x, !is.na(.x), .f) %>% 
    purrr::map_chr(1L) %>% return()
}

# Issuesの事前展開
load("./_redmine_issues_all.RData_")

issues_2018 <- issues %>% 
  dplyr::select(id, created_on, closed_on, tracker, status, priority,
                category, author, assigned_to, subject) %>% 
  dplyr::mutate_if(is.list, map_if_chr, 'name') %>% 
  dplyr::mutate(open = lubridate::as_date(created_on),
                close = lubridate::as_date(closed_on)) %>% 
  dplyr::select(-created_on, -closed_on) %>% 
  dplyr::filter(open >= "2018-1-1")

# 基準となる週番号
weeks <- data.frame(week = c(1:53))
```

# Summary

## Coloumn {data-width=650} {.tabset}

### Overall
```{r}
issues_2018 %>% 
  dplyr::count(tracker, status) %>% 
  tidyr::spread(tracker, n) %>% knitr::kable(caption = "All isseues")
  # DT::datatable(caption = "All issues")
```
```{r}
issues_2018 %>% 
  dplyr::count(status, priority) %>% 
  tidyr::spread(priority, n) %>% knitr::kable(caption = "All isseues")
  # DT::datatable(caption = "All issues")
```

### Defect
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect") %>% 
  dplyr::count(status, priority) %>% 
  tidyr::spread(priority, n) %>% knitr::kable(caption = "Defect issues")
  # DT::datatable(caption = "Defect issues")
```

### Feature
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Feature") %>% 
  dplyr::count(status, priority) %>% 
  tidyr::spread(priority, n) %>% knitr::kable(caption = "Feature issues")
  # DT::datatable(caption = "Defect issues")
```

### Patch
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Patch") %>% 
  dplyr::count(status, priority) %>% 
  tidyr::spread(priority, n) %>% knitr::kable(caption = "Feature issues")
  # DT::datatable(caption = "Defect issues")
```


### New issues
```{r, echo=FALSE}
issues_2018 %>% 
  dplyr::filter(status == "New") %>% 
  dplyr::select(id, open, priority, category, subject) %>% 
  DT::datatable(options = list(pageLength = 25))
```


## Column {data-width=350}  {.tabset}

### Overall
```{r}
# 対象チケットの洗い出し
tmp_issues <- issues_2018 %>% 
  # dplyr::filter(tracker == "Defect") %>% 
  dplyr::mutate(status = dplyr::if_else(status == "Closed", status, "Open"),
                open = lubridate::week(open),
                close = lubridate::week(close)) %>% 
  dplyr::select(id, open, close, status)

# チケット最終週
max_week <- max(tmp_issues$open, tmp_issues$close, na.rm = TRUE)

# チケットオープンの集計
open <- tmp_issues %>% 
  dplyr::count(open) %>% 
  dplyr::rename(week = open, open = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(open = dplyr::if_else(is.na(open) & week <= max_week, 0L, open)) %>% 
  dplyr::mutate(cum_open = cumsum(open)) 

close <- tmp_issues %>% 
  dplyr::filter(status == "Closed") %>% 
  dplyr::count(close) %>% 
  dplyr::rename(week = close, close = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(close = dplyr::if_else(is.na(close) & week <= max_week, 0L, close)) %>% 
  dplyr::mutate(cum_close = cumsum(close)) 


(open %>% 
  dplyr::full_join(close, by = "week") %>% 
  dplyr::select(week, open = cum_open, closed = cum_close) %>% 
  tidyr::gather(key = "Status", value, -week) %>% 
  ggplot2::ggplot(ggplot2::aes(x = week)) + 
    ggplot2::geom_line(ggplot2::aes(y = value, colour = Status)) + 
    ggplot2::labs(y = "", title = "All issues") ) %>% 
  plotly::ggplotly()
```

### Defect
```{r}
# 対象チケットの洗い出し
tmp_issues <- issues_2018 %>% 
  dplyr::filter(tracker == "Defect") %>% 
  dplyr::mutate(status = dplyr::if_else(status == "Closed", status, "Open"),
                open = lubridate::week(open),
                close = lubridate::week(close)) %>% 
  dplyr::select(id, open, close, status)

# チケット最終週
max_week <- max(tmp_issues$open, tmp_issues$close, na.rm = TRUE)

# チケットオープンの集計
open <- tmp_issues %>% 
  dplyr::count(open) %>% 
  dplyr::rename(week = open, open = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(open = dplyr::if_else(is.na(open) & week <= max_week, 0L, open)) %>% 
  dplyr::mutate(cum_open = cumsum(open)) 

close <- tmp_issues %>% 
  dplyr::filter(status == "Closed") %>% 
  dplyr::count(close) %>% 
  dplyr::rename(week = close, close = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(close = dplyr::if_else(is.na(close) & week <= max_week, 0L, close)) %>% 
  dplyr::mutate(cum_close = cumsum(close)) 


(open %>% 
  dplyr::full_join(close, by = "week") %>% 
  dplyr::select(week, open = cum_open, closed = cum_close) %>% 
  tidyr::gather(key = "Status", value, -week) %>% 
  ggplot2::ggplot(ggplot2::aes(x = week)) + 
    ggplot2::geom_line(ggplot2::aes(y = value, colour = Status)) + 
    ggplot2::labs(y = "", title = "Defect") ) %>% 
  plotly::ggplotly()
```

### Feature
```{r}
# 対象チケットの洗い出し
tmp_issues <- issues_2018 %>% 
  dplyr::filter(tracker == "Feature") %>% 
  dplyr::mutate(status = dplyr::if_else(status == "Closed", status, "Open"),
                open = lubridate::week(open),
                close = lubridate::week(close)) %>% 
  dplyr::select(id, open, close, status)

# チケット最終週
max_week <- max(tmp_issues$open, tmp_issues$close, na.rm = TRUE)

# チケットオープンの集計
open <- tmp_issues %>% 
  dplyr::count(open) %>% 
  dplyr::rename(week = open, open = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(open = dplyr::if_else(is.na(open) & week <= max_week, 0L, open)) %>% 
  dplyr::mutate(cum_open = cumsum(open)) 

close <- tmp_issues %>% 
  dplyr::filter(status == "Closed") %>% 
  dplyr::count(close) %>% 
  dplyr::rename(week = close, close = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(close = dplyr::if_else(is.na(close) & week <= max_week, 0L, close)) %>% 
  dplyr::mutate(cum_close = cumsum(close)) 


(open %>% 
  dplyr::full_join(close, by = "week") %>% 
  dplyr::select(week, open = cum_open, closed = cum_close) %>% 
  tidyr::gather(key = "Status", value, -week) %>% 
  ggplot2::ggplot(ggplot2::aes(x = week)) + 
    ggplot2::geom_line(ggplot2::aes(y = value, colour = Status)) + 
    ggplot2::labs(y = "", title = "Feature") ) %>% 
  plotly::ggplotly()
```

### Patch
```{r}
# 対象チケットの洗い出し
tmp_issues <- issues_2018 %>% 
  dplyr::filter(tracker == "Patch") %>% 
  dplyr::mutate(status = dplyr::if_else(status == "Closed", status, "Open"),
                open = lubridate::week(open),
                close = lubridate::week(close)) %>% 
  dplyr::select(id, open, close, status)

# チケット最終週
max_week <- max(tmp_issues$open, tmp_issues$close, na.rm = TRUE)

# チケットオープンの集計
open <- tmp_issues %>% 
  dplyr::count(open) %>% 
  dplyr::rename(week = open, open = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(open = dplyr::if_else(is.na(open) & week <= max_week, 0L, open)) %>% 
  dplyr::mutate(cum_open = cumsum(open)) 

close <- tmp_issues %>% 
  dplyr::filter(status == "Closed") %>% 
  dplyr::count(close) %>% 
  dplyr::rename(week = close, close = n) %>% 
  dplyr::full_join(weeks, .,by = "week") %>% 
  dplyr::mutate(close = dplyr::if_else(is.na(close) & week <= max_week, 0L, close)) %>% 
  dplyr::mutate(cum_close = cumsum(close)) 

(open %>% 
  dplyr::full_join(close, by = "week") %>% 
  dplyr::select(week, open = cum_open, closed = cum_close) %>% 
  tidyr::gather(key = "Status", value, -week) %>% 
  ggplot2::ggplot(ggplot2::aes(x = week)) + 
    ggplot2::geom_line(ggplot2::aes(y = value, colour = Status)) + 
    ggplot2::labs(y = "", title = "Patch") ) %>% 
  plotly::ggplotly()
```


### Stays
```{r, message = FALSE, warning=FALSE}
(issues_2018 %>% 
  dplyr::filter(status != "Closed") %>% 
  dplyr::mutate(days = lubridate::today() - open + 1) %>% 
  ggplot2::ggplot(ggplot2::aes(x = days, fill = priority)) + 
    ggplot2::geom_histogram(alpha = 0.6, position = "identity") + 
    ggplot2::labs(x = "滞留日数", y = "", title = "Open issues")) %>% 
  plotly::ggplotly()
```


# Defect

## Coloumn {data-width=150}

### New
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect" & status == "New") %>% 
  dplyr::count() %>% 
  flexdashboard::valueBox(caption = "New", color = "danger")
```

### Needs feedback
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect" & status == "Needs feedback") %>% 
  dplyr::count() %>% 
  flexdashboard::valueBox(caption = "Needs feedback", color = "warning")
```

### Responsed
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect" & status == "Responsed") %>% 
  dplyr::count() %>% 
  flexdashboard::valueBox(caption = "Responsed", color = "primary")
```


### Confirmed
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect" & status == "Confirmed") %>% 
  dplyr::count() %>% 
  flexdashboard::valueBox(caption = "Confirmed", color = "primary")
```

### Resolved
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect" & status == "Resolved") %>% 
  dplyr::count() %>% 
  flexdashboard::valueBox(caption = "Resolved", color = "success")
```

### Closed
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect" & status == "Closed") %>% 
  dplyr::count() %>% 
  flexdashboard::valueBox(caption = "Closed", color = "success")
```


## Coloumn {data-width=850} {.tabset}

### Overall
```{r}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect") %>% 
  dplyr::count(category, status) %>% 
  tidyr::spread(status, n) %>% 
  DT::datatable(options = list(pageLength = 25), caption = "Defect issues")
```

```{r, eval=FALSE}
issues_2018 %>% 
  dplyr::filter(tracker == "Defect") %>% 
  dplyr::count(status) %>% 
  ggplot2::ggplot(ggplot2::aes(x = "status", y = n, fill = status)) + 
    ggplot2::geom_bar(stat = "identity", width = 1, alpha = 0.75) +
    ggplot2::coord_polar(theta = "y", direction = 1) +
    ggplot2::guides(fill = guide_legend(reverse = TRUE)) + 
    ggplot2::labs(x = "", y = "")
```


### New

#### 分割可能？
```{r}
summary(issues_2018) %>% broom::tidy()
```

#### 分割可能？
```{r}
summary(iris)
````

### Needs feedback

### Responsed

### Confirmed

### Reolved

### Closed

# Feature

# Patch
