---
title: "Rのすゝめ解答集"
output:
  slidy_presentation:
    df_print: "paged"
    font_adjustment: +1
    highlight: pygments
    theme: cerulean
  # beamer_presentation: 
  #   incremental: yes
  #   toc: yes
  # ioslides_presentation:
  #   df_print: "paged"
  #   highlight: pygments
  #   theme: cerulean
  #   smaller: true
  #   widescreen: true
# runtime: shiny_prerendered
---

```{r setup, include=FALSE, message=FALSE}
# 共通chunkオプションの指定
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

require(DT)
require(tidyverse)
require(gridExtra)
tidyverse::tidyverse_conflicts()

# Windows環境ではデータフレームが正しく表示されないためDTパッケージを用いた
# 表示を行う必要があるため環境を判別して表示方法を変える
df_print <- function(df){
  if (Sys.info()[1] == "Windows") {
    DT::datatable(df, class = 'compact display nowrap')
  } else {
    df
  }
}

# setupチャンクで作成したオブジェクトはどこからでも参照可能
if (Sys.info()[1] == "Windows") {
# ODC分析データ用ファイルパス
  file_odc <- "C:\\Users\\suzuki\\Dropbox\\RStudio\\cabinet\\program\\basics\\data\\odc.csv"
  # file_odc <- "C:\\Users\\sampo\\Dropbox\\RStudio\\cabinet\\program\\basics\\data\\odc.csv"
  
# Redmine分析データ用ファイルパス
  file_redmine <- "C:\\Users\\suzuki\\Dropbox\\RStudio\\cabinet\\program\\basics\\data\\issues.csv"
  # file_redmine <- "C:\\Users\\sampo\\Dropbox\\RStudio\\cabinet\\program\\basics\\data\\issues.csv"
} else {
  file_odc <- "/home/sampo/Dropbox/RStudio/cabinet/program/basics/data/odc.csv"
  file_redmine <- "/home/sampo/Dropbox/RStudio/cabinet/program/basics/data/issues.csv"
  # file_odc <- "/home/vaio/Dropbox/RStudio/cabinet/program/basics/data/odc.csv"
  # file_redmine <- "/home/vaio/Dropbox/RStudio/cabinet/program/basics/data/issues.csv"
}

odc_data <- read_csv(file_odc, locale = locale(encoding = "CP932"),
                     progress = FALSE)
bugs <- read_csv(file_redmine, locale = locale(encoding = "UTF-8"),
                 progress = FALSE)
```

## Answer
```{r}
odc_data %>% 
  dplyr::select(Status = 'ステータス', Result = '解決状況', Date = '発生日',
                Rank = '障害ランク', Step = '欠陥検出工程',
                Trigger = '発生トリガー', Type = '欠陥実装タイプ',
                Dtype = '欠陥タイプ') %>% 
  dplyr::filter(Dtype != "（障害ではない）") %>% 
  dplyr::count(Step, Dtype) %>% 
  ggplot2::ggplot(aes(x = Step, y = n)) +
    ggplot2::geom_bar(aes(fill = Dtype), stat = "identity", alpha = 0.5) +
    ggplot2::ggtitle("検出工程別欠陥タイプ", 
                     subtitle = paste(Sys.Date(), "現在", sep="")) +
    ggplot2::xlab("欠陥検出工程") + ggplot2::ylab("件数") +
    ggplot2::scale_fill_discrete(name = "欠陥タイプ")
```
