---
title: "links"
author: "Sampo Suzuki"
output: html_document
---

<!-- SQiP and others -->
[0]: https://sites.google.com/site/kantometrics/ {target="_blank" title="データ分析勉強会"}
[1]: https://k-metrics.github.io/ {target="_blank" title="データ分析勉強会アーカイブ"}
[2]: https://www.juse.or.jp/sqip/ {target="_blank" title="SQiP by 日科技連"}
[3]: http://www.juse-p.co.jp/ {target="_blank" title="日科技連出版"}
[6]: http://gacco.org/ {target="_blank" title="gacco, The Japan MOOC"}

<!-- Books -->
[B2]: https://book.mynavi.jp/ec/products/detail/id=39763 {target="_blank" title="みんなのR(マイナビブックス)"}
[B3]: http://gihyo.jp/book/2017/978-4-7741-8812-6 {target="_blank" title="パーフェクトR(技術評論社)"}
[B4]: http://www.c-r.com/book/detail/1076 {target="_blank" title="改訂3版 R言語逆引きハンドブック(C&R研究所)"}
[B5]: http://www.natsume.co.jp/book/index.php?action=show&code=004957 {target="_blank" title="史上最強 図解 これならわかる！統計学(ナツメ出版)"}
[B6]: http://www.natsume.co.jp/book/index.php?action=show&code=005181 {target="_blank" title="史上最強 図解 これならわかる！ベイズ統計学(ナツメ出版)"}

<!-- 共立出版 -->
[BK1]: http://www.kyoritsu-pub.co.jp/series/23/ {target="_blank" title="Rで学ぶデータサイエンス　全20巻"}
[BK2]: http://www.kyoritsu-pub.co.jp/series/185/ {target="_blank" title="シリーズ Useful R　全10巻"}
[BK3]: http://www.kyoritsu-pub.co.jp/series/205/ {target="_blank" title="Wonderful R　全10巻"}
[BK4]: http://www.kyoritsu-pub.co.jp/series/204/ {target="_blank" title="統計学One Point"}
[BK5]: http://www.kyoritsu-pub.co.jp/series/20/ {target="_blank" title="データサイエンス・シリーズ　全12巻"}
[BK6]: http://www.kyoritsu-pub.co.jp/bookdetail/9784320123939 {target="_blank" title="R言語徹底解説(共立出版)"}
[BK7]: http://www.kyoritsu-pub.co.jp/bookdetail/9784320112414 {target="_blank" title="Rで楽しむ統計(共立出版)"}
[BK8]: http://www.kyoritsu-pub.co.jp/bookdetail/9784320124264 {target="_blank" title="Rプログラミング本格入門(共立出版)"}

<!-- 日科技連出版 -->
[BN1]: http://www.juse-p.co.jp/cgi-bin/html.pl5?i=ISBN978-4-8171-9447-3 {target="_blank" title="データ指向のソフトウェア品質マネジメント"}
[BN2]: http://www.juse-p.co.jp/cgi-bin/html.pl5?i=ISBN978-4-8171-9558-6 {target="_blank" title="ソフトウェアメトリクス統計分析入門"}
[BN3]: http://www.juse-p.co.jp/cgi-bin/html.pl5?i=ISBN4-8171-0294-2 {target="_blank" title="統計的方法のしくみ"}

<!-- O'Reilly Japan -->
[BO1]: https://www.oreilly.co.jp/books/9784873118147/ {target="_blank" title="Rではじめるデータサイエンス(O'Reilly)"}
[BO2]: https://www.oreilly.co.jp/books/9784873117157/ {target="_blank" title="RStudioではじめるRプログラミング入門(O'Reilly)"}
[BO3]: https://www.oreilly.co.jp/books/9784873116518/ {target="_blank" title="Rクイックリファレンス(R'Reilly)"}
[BO4]: https://www.oreilly.co.jp/books/9784873115795/ {target="_blank" title="アート・オブ・Rプログラミング(R'Reilly)"}
[BO5]: https://www.oreilly.co.jp/books/9784873115337/ {target="_blank" title="Rクックブック(O'Reilly)"}
[BO6]: https://www.oreilly.co.jp/books/9784873116532/ {target="_blank" title="Rグラフィックスクックブック(O'Reilly)"}

<!-- 東京図書 -->
[BT1]: http://www.tokyo-tosho.co.jp/books/ISBN978-4-489-02150-3.html {target="_blank" title="統計学　統計検定１級対応"}
[BT2]: http://www.tokyo-tosho.co.jp/books/978-4-489-02227-2/ {target="_blank" title="統計学基礎　統計検定２級対応"}
[BT3]: http://www.tokyo-tosho.co.jp/books/ISBN978-4-489-02132-9.html {target="_blank" title="データの分析　統計検定３級対応"}
[BT4]: http://www.tokyo-tosho.co.jp/books/ISBN978-4-489-02145-9.html {target="_blank" title="資料の活用　統計検定４級対応"}

<!-- Docker -->
[DoC]: https://www.docker.com/ {target="_blank" title="Docker"}
[DfW]: https://docs.docker.com/docker-for-windows/ {target="_blank" title="Docker for Windows"}
[DfWi]: https://docs.docker.com/docker-for-windows/install/ {target="_blank" title="Install Docker for Windows"}
[DoCD]: https://docs.docker.com/ {target="_blank" title="Docker Documentation"}
[DoCDJ]: http://docs.docker.jp/ {target="_blank" title="Docker ドキュメント日本語化Pj"}

<!-- eBooks -->
[EB1]: http://r4ds.had.co.nz/ {target="_blank" title="R for Data Science"}
[EB2]: http://tidytextmining.com/ {target="_blank" title="Text Mining with R"}

<!-- Net Community -->
[C1]: http://qiita.com/uri/items/5583e91bb5301ed5a4ba {target="_blank" title="R-wakalang"}
[C2]: http://www.okadajp.org/RWiki/ {target="_blank" title="RjpWiki"}
[C3]: http://seekr.jp/ {target="_blank" title="seek R"}

<!-- Style Guide -->
[SG1]: https://google.github.io/styleguide/Rguide.xml {target="_blank" title="Google's R style guide"}
[SG2]: http://adv-r.had.co.nz/Style.html {target="_blank" title="Advanced R style guide"}
[SG3]: http://style.tidyverse.org/ {target="_blank" title="The tidyverse style guide"}
[SG4]: https://msu.edu/~idworkin/ZOL851_style_guide.html {target="_blank" title="R style guide for ZOL851"}

<!-- Creative Commons -->
[CC]: http://creativecommons.org/licenses/by-nc-sa/4.0/deed.ja {target="_blank" title="CC BY-NC-SA 4.0"}
[CCI]: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png {target="_blank" title="CC BY-NC-SA 4.0 icon"}
[CCBY]: https://creativecommons.org/licenses/by/4.0/deed.ja {target="_blank" title="CC BY 4.0"}

<!-- Others -->
[MD]: http://www.markdown.jp/what-is-markdown/ {target="_blank" title="Markdownとは (日本語Markdownユーザ会)"}
[YAML]: http://yaml.org/ {target="_blank" title="YAML Ain't Markup Language"}
[U]: https://www.ubuntu.com/ {target="_blank" title="The leading operating system for PCs, IoT devices, servers and the cloud"}
[UAP]: https://www.ubuntulinux.jp/japanese {target="_blank" title="追加パッケージの利用方法"}
[UJT]: https://www.ubuntulinux.jp/ {target="_blank" title="Ubuntu Japanese Team"}
[UDJR]: https://www.ubuntulinux.jp/japanese {target="_blank" title="Ubuntu Desktop Japanese Remix"}

<!-- R -->
[R]: https://www.r-project.org/ {target="_blank" title="The R Project"}
[CRAN]: https://cran.r-project.org/ {target="_blank" title="CRAN, The Comprehensive R Archive Network"}
[CRANPL]: https://cran.r-project.org/web/packages/available_packages_by_name.html {target="_blank" title="CRAN Packages List"}
[CRANPLJ]: http://www.trifields.jp/statistical-analysis-r-cran-packages-341 {target="_blank" title="CRANパッケージリスト(非公式)"}
[CRANTV]: https://cran.r-project.org/web/views/ {target="_blank" title="CRAN Task View"}
[CRANTVJ]: http://www.trifields.jp/r-cran-task-views-639 {target="_blank" title="CRAN Task View(非公式日本語版)"}
[ISM]: https://cran.ism.ac.jp/ {target="_blank" title="CRAN Mirror at ISM"}

[CfR]: http://www.cookbook-r.com/ {target="_blank" title="Cookbook for R (English)"}


<!-- R Packages -->
[DT]: https://rstudio.github.io/DT/ {target="_blank" title="An R interface to the DataTables library"}
[flexdb]: http://rmarkdown.rstudio.com/flexdashboard/index.html {target="_blank" title="flexdashboard for R"}
[flexdashboard]: http://rmarkdown.rstudio.com/flexdashboard/index.html {target="_blank" title="flexdashboard for R"}
[formatr]: https://yihui.name/formatr/ {target="_blank" title="Format R code automatically"}
[htmlwidgets]: http://www.htmlwidgets.org/ {target="_blank" title="htmlwidgets for R"}
[knitr]: https://yihui.name/knitr/ {target="_blank" title="Elegant, flexible and fast dynamic report generation with R"}
[learnr]: https://rstudio.github.io/learnr/ {target="_blank" title="Interactive Tutorials for R"}
[Rcmdr]: https://socialsciences.mcmaster.ca/jfox/Misc/Rcmdr/ {target="_blank" title="The R Commander: A Basic-Statistics GUI for R"}
[rmarkdown]: https://cran.r-project.org/web/packages/rmarkdown/index.html {target="_blank" title="Dynamic Documents for R"}
[shiny]: https://shiny.rstudio.com/ {target="_blank" title="Shiny by RStudio"}
[shinydb]: http://rstudio.github.io/shinydashboard/index.html {target="_blank" title="Shiny Dashboard"}
[shinydashboard]: http://rstudio.github.io/shinydashboard/index.html {target="_blank" title="Shiny Dashboard"}
[tidy]: http://tidyverse.org/ {target="_blank" title="The tidyverse"}
[tidyverse]: https://cran.r-project.org/web/packages/tidyverse/index.html {target="_blank" title="Easily Install and Load the 'Tidyverse'"}

<!-- RStudio -->
[RS]: https://www.rstudio.com/products/RStudio/ {target="_blank" title="RStudio"}
[RStudio]: https://www.rstudio.com/products/RStudio/ {target="_blank" title="RStudio"}
[RSD]: https://www.rstudio.com/products/RStudio/#Desktopx {target="_blank" title="RStudio Desktop"}
[RSS]: https://www.rstudio.com/products/RStudio/#Server {target="_blank" title="RStudio Server"}
[RM]: http://rmarkdown.rstudio.com/ {target="_blank" title="R Markdown from RStudio Inc"}
[RMD]: http://rmarkdown.rstudio.com/ {target="_blank" title="R Markdown from RStudio Inc"}
[RSH]: https://github.com/rstudio/RStartHere {target="_blank" title="RStartHere, RStudio Inc"}
[R4DS]: http://r4ds.had.co.nz/ {target="_blank" title="R for Data Science, Hadley Wickham and Garrett Grolemund"}

<!-- Docker -->
[DC]: https://www.docker.com/ {target="_blank" title="Docker"}
[RC]: https://hub.docker.com/u/rocker/ {target="_blank" title="Rocker Project"}
[DCI]: https://store.docker.com/editions/community/docker-ce-server-ubuntu?tab=description {target="_blank" title="Install Docker CE"}
[DCPI]: https://docs.docker.com/engine/installation/linux/linux-postinstall/ {target="_blank" title="Post-onstallation"}

<!-- Cabinet Pages -->
[I]: https://k-metrics.github.io/cabinet/program/ "Import"
[T]: https://k-metrics.github.io/cabinet/transform/ "Tidy/Transform"
[V]: https://k-metrics.github.io/cabinet/visualize/ "Visualize"
[M]: https://k-metrics.github.io/cabinet/model/ "Model/Infer"
[C]: https://k-metrics.github.io/cabinet/communicate/ "Communicate/Automate"
[P]: https://k-metrics.github.io/cabinet/program/ "Program"