---
title: "R Setup Overall"
output: 
  html_document:  
    number_section: no
    toc: yes
---

<!-- Include Common Links -->
```{r child="../common/links.Rmd"}
```

**R Setup**では[R][R]分析環境の導入構築方法やツール、ライブラリ類に関する情報を整理しています。  

# R Desktop環境
[R][R]のデスクトップ環境の大まかな導入構築手順は以下の通りです。詳細は各ページでご確認下さい。

手順 | 実施内容                        | 備考
-----|---------------------------------|----------------------------------------
1    | [Rのインストール][PE1]          | 
2    | [ツールのインストール][PE2]     | Winodws環境のみ（必須）
3    | [Rcmdrのインストール][PE3]      | データ分析勉強会参加者のみ
4    | [RStudioのインストール][PE4]    | Desktop Version
5    | [パッケージのインストール][PE5] | 必要に応じて
6    | [Rのアップデート][PE6]          | R本体を更新する場合
7    | Texのインストール               | R MarkdownでPDFを作成する場合
8    | Git/SVNのインストール           | バージョン管理システムを利用する場合

　  

## チュートリアル環境
データ分析勉強会のチュートリアル環境の準備に関しては以下の手順もご参照下さい。  

手順 | 実施内容                        | 備考
-----|---------------------------------|----------------------------------------
8    | [チュートリアル環境][PE8]       | データ分析勉強会向けの環境作成確認方法
　  

# RStudio Server環境
[RStudio][RS]にはデスクトップ環境だけでなくサーバ環境も用意されています。サーバ環境を用いることで個々人のデスクトップ環境に依存することない開発環境の導入が実現可能になります。業務で複数人で利用する場合はサーバ環境の構築がおすゝめですが、少人数やサーバ機器の準備等が難しい場合は仮想環境を用いたサーバ環境の構築がおすゝめです。それ以外にもCRAN以外から提供されている試験的なパッケージをメイン環境を損ねることなく使いたい場合にも便利です。  
　  

## Rocker
[RStudio][RS]サーバ環境を最も手軽に使う方法が[Docker](https://www.docker.com/)の利用です。[Rockder](https://github.com/rocker-org/rocker)というDockerイメージが公開されていますのでこれを利用するのが最も簡単です。詳しくは[こちら][PES]のページを参照して下さい。  

---

<!-- Include Footer -->
```{r child="../common/footer.Rmd"}
```

<!-- Local Pages -->
[PE1]: ./env_install.html "Install R"
[PE2]: ./env_install_tls.html "Install Rtools"
[PE3]: ./env_install_pkg.html "Install Rcmdr"
[PE4]: ./env_install_dtp.html "Install RStudio"
[PE5]: ./env_install_pkg.html "Install Packages"
[PE6]: ./env_update_r.html "Update R"
[PE7]: ./env_install_tex.html "Install TeX Live"
[PE8]: ./env_install_git.html "Install Git/SVN"

[PE9]: ./env_install_chk.html "Install Check"
[PES]: ./env_install_svr.html "Install RStudio Server"
