---
title: "信頼区間と予測区間"
author: "Sampo Suzuki"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(car)

# 組込データセット"mtcars"を読み込む
data(mtcars, package = "datasets")

# シリンダー数を層別因子にする
mtcars$f.cyl <- as.factor(mtcars$cyl)

# 線形回帰を計算する
res.lm <- lm(mpg ~ hp, data = mtcars)

# 横軸の区間範囲はグラフから読み取った値とする
xmin <- 50
xmax <- 350
step <- 10
ymin <- 10
ymax <- 35
new <- data.frame(hp = seq(xmin, xmax, step))

# 予測区間を計算する
pred.lm <- predict(res.lm, new, interval = "prediction")

# 信頼区間を計算する
conf.lm <- predict(res.lm, new, interval = "confidence")

# プロットの準備
x.plot <- seq(xmin, xmax, step)


# 回帰直線をプロットする
plot(x.plot, pred.lm[, 1], type = "l", xlim = c(xmin, xmax), ylim = c(ymin, ymax),
     xlab = "", ylab = "")

# 上書きを許可する
par(new = TRUE)

# 予測範囲(下限)をプロットする
plot(x.plot, pred.lm[, 2], type = "l", xlim = c(xmin, xmax), ylim = c(ymin, ymax),
     lty = 2, xlab = "", ylab = "", col = "red")

# 上書きを許可する
par(new = TRUE)

# 信頼範囲(下限)をプロットする
plot(x.plot, conf.lm[, 2], type = "l", xlim = c(xmin, xmax), ylim = c(ymin, ymax),
     lty = 3, xlab = "", ylab = "", col = "blue")

# 上書きを許可する
par(new = TRUE)

# 予測範囲(上限)をプロットする
plot(x.plot, pred.lm[, 3], type = "l", xlim = c(xmin, xmax), ylim = c(ymin, ymax),
     lty = 2, xlab = "", ylab = "", col = "red")

# 上書きを許可する
par(new = TRUE)

# 信頼範囲(上限)をプロットする
plot(x.plot, conf.lm[, 3], type = "l", xlim = c(xmin, xmax), ylim = c(ymin, ymax),
     lty = 3, xlab = "", ylab = "", col = "blue")

# 上書きを許可する
par(new = TRUE)

# 散布図をプロットする
plot(mtcars$hp, mtcars$mpg, type = "p", xlim = c(xmin, xmax), ylim = c(ymin, ymax),
     lty = 2, ylab = "mpg", xlab = "hp")

# 上書きを禁止する
par(new = FALSE)

# R^2の値を表示する
mtext(substitute(paste(R^2, "=", x),
                 list(x = round(summary(res.lm)$r.squared, digits = 5))),
      line = 1, col = "red", adj = 0)

# 凡例を描画する
leglabels <- c("回帰直線", "予測区間", "信頼区間")
leglty <- c(1, 2, 3)
legcol <- c("black", "red", "blue")
legend("topright", legend = leglabels, lty = leglty, col = legcol, lwd = 1)
```

```{r}
require(car)

# 組込データセット"mtcars"を読み込む
data(mtcars, package = "datasets")

# シリンダー数を層別因子にする
mtcars$f.cyl <- as.factor(mtcars$cyl)

# Rcmdrで散布図を作画する（周辺箱ひげ図は描画しない）
scatterplot(mpg ~ hp, reg.line = lm, smooth = FALSE, spread = FALSE,
            id.method = 'mahal', id.n = 2, boxplots = FALSE, span = 0.5,
            data = mtcars)

# 線形回帰直線を計算する(Rcmderで計算しても可)
result.lm <- lm(mpg ~ hp, data = mtcars)

# 予測区間は最小値と最大値を10等分したものとする
min <- min(mtcars$hp)
max <- max(mtcars$hp)
step <- abs(max - min) / 10
new <- data.frame(hp = seq(min, max, step))

# 予測区間を計算する
result.pre <- predict(result.lm, new, interval = "prediction")

# 信頼区間を計算する
result.con <- predict(result.lm, new, interval = "confidence")

# 予測区間を散布図に上書きする
lines(new[, 1], result.pre[, 2], col = "red", lty = 2)    # 下側
lines(new[, 1], result.pre[, 3], col = "red", lty = 2)    # 上側

# 信頼区間を散布図に上書きする
lines(new[, 1], result.con[, 2], col = "blue", lty = 3)   # 下側
lines(new[, 1], result.con[, 3], col = "blue", lty = 3)   # 上側

# R^2の値を表示する
mtext(substitute(paste(R^2, "=", x),
                 list(x = round(summary(result.lm)$r.squared, digits = 5))),
      line = 1, col = "red", adj = 0)

# 凡例を描画する
leglabels <- c("回帰直線", "予測区間", "信頼区間")
leglty <- c(1, 2, 3)
legcol <- c("green", "red", "blue")
legend("topright", legend = leglabels, lty = leglty, col = legcol, lwd = 1)

```

---
