---
title: "scatterplot"
output:
  html_document:
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(gridExtra)
require(DT)
require(knitr)
require(car)
require(maptools)

tidyverse::tidyverse_conflicts()

class <- c("display cell-border compact")
style <- ifelse(!interactive(), c("bootstrap"), c("default"))
```

# 散布図にラベルを表示する

```{r}
# 組込データセット"mtcars"を読み込む
data(mtcars, package = "datasets")

# 散布図を描く（周辺箱ひげ図と外れ値ラベルは描かない）
#   周辺箱ひげ図を描くと描画原点と軸原点がずれるようで、ラベル表示位置がズレます
scatterplot(mpg ~ hp, data = mtcars, reg.line = lm, smooth = FALSE, span = 0.5,
            spread = FALSE, boxplots = FALSE)

# 全点に対してラベル（シリンダ数）を描く
with(mtcars, pointLabel(x = hp, y = mpg, labels = row.names.data.frame(mtcars),
                        col = "red", cex = 0.75))
```


```{r, eval=FALSE}
Dataset <- read.table("clipboard", header=TRUE, sep="\t", na.strings="NA",
                      dec=".", strip.white=TRUE, row.names=1)
```

```{r}
# 組込データセット"mtcars"を読み込む
data(mtcars, package="datasets")

# シリンダ数を層別因子にする
mtcars <- within(mtcars, {
    f.cyl <- as.factor(cyl)
})

# 散布図を描く
#   データセット内に"row.names"というデータ行があると自動的にそのデータ行が使用されます
scatterplot(mpg~hp, reg.line=lm, smooth=FALSE, spread=FALSE, id.method='mahal',
            id.n = 2, boxplots='xy', span=0.5, data=mtcars)

# 散布図を描く
#   ラベルとして層別因子にしたシリンダ数を利用した場合
scatterplot(mpg~hp, reg.line=lm, smooth=FALSE, spread=FALSE,
            labels=mtcars$f.cyl, id.method='mahal', id.n = 2, boxplots='xy',
            span=0.5, data=mtcars)
```

