---
title: "Visualize"
---

Visualizeとは、その名の通りデータを可視化（見える化）するためのプロセスです。データを数値要約しただけでは分かりにくいデータの分布傾向等を見るために可視化（見える化）は有用な方法です。

## base
Rの標準グラッフィックパッケージである`graphics`によるグラフ描画に関する情報を整理してあります。

## ggplot2
今やRのデファクトグラッフィックパッケージとも言える`ggplot2`によるグラフ描画に関する情報を整理してあります。

## htmlwidgets
htmlwidgetsはインタラクティブなデータ表示を行うためのJavaScriptを用いた描画ライブラリです。htmlwidgetsを用いた便利な可視化パッケージに関する情報を整理してあります。

## Others
その他、可視化に関する情報を整理してあります。

# {.tabset}

## 権利と免責 {.unnumbered}
* 本資料の著作権は原則として著作者に帰属します。ただし、引用した演習の設問等の著作権は原著作者が所有しています。
* 本資料は無保証です。本資料を使用することによって生じる、いかなる直接的・間接的損害について著作者はいかなる責任、サポート義務を負いません。

---

## ライセンス {.unnumbered}
本資料は[クリエイティブ・コモンズ 表示 - 非営利 - 継承 4.0 国際ライセンス][CC]の下に提供されています。

---

[0]: https://sites.google.com/site/kantometrics/ "データ分析勉強会"
[1]: https://k-metrics.github.io/ "データ分析勉強会アーカイブ"
[2]: https://www.juse.or.jp/sqip/ "SQiP"
[3]: http://www.juse-p.co.jp/ "日科技連出版"
[4]: http://www.juse-p.co.jp/cgi-bin/html.pl5?i=ISBN978-4-8171-9447-3 "データ指向のソフトウェア品質マネジメント"
[5]: http://www.juse-p.co.jp/cgi-bin/html.pl5?i=ISBN978-4-8171-9558-6 "ソフトウェアメトリクス統計分析入門"
[6]: http://gacco.org/ "gacco, The Japan MOOC"

[CC]: http://creativecommons.org/licenses/by-nc-sa/4.0/deed.ja "CC BY-NC-SA 4.0"
[CCI]: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png "CC BY-NC-SA 4.0 icon"

[R]: https://www.r-project.org/ "The R Project"
[RS]: https://www.rstudio.com/ "RStudio"
[RSD]: https://www.rstudio.com/products/RStudio/#Desktop "RStudio Desktop"
[RM]: http://rmarkdown.rstudio.com/ "R Markdown form RStudio"
[RSH]: https://github.com/rstudio/RStartHere "R Start Here"

[I]: https://k-metrics.github.io/cabinet/program/ "Import"
[T]: https://k-metrics.github.io/cabinet/transform/ "Tidy/Transform"
[V]: https://k-metrics.github.io/cabinet/visualize/ "Visualize"
[M]: https://k-metrics.github.io/cabinet/model/ "Model/Infer"
[C]: https://k-metrics.github.io/cabinet/communicate/ "Communicate/Automate"
[P]: https://k-metrics.github.io/cabinet/program/ "Program"