---
title: "rvest"
author: "Sampo Suzuki"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

require(rvest)
require(xml2)
require(tidyverse)
```

# ポケモンGO
```{r, include=FALSE}
site_url <- "https://appmedia.jp/pokemon_go/350150"
xpath_ss <- "/html/body/div[3]/div[1]/div/div/div[3]/div[2]/div/div[2]/table[4]"
xpath_s <- "/html/body/div[3]/div[1]/div/div/div[3]/div[2]/div/div[2]/table[5]"
xpath_ap <- "/html/body/div[3]/div[1]/div/div/div[3]/div[2]/div/div[2]/table[6]"
xpath_a <- "/html/body/div[3]/div[1]/div/div/div[3]/div[2]/div/div[2]/table[7]"
```

## Rank SS
```{r}
(rank_ss <- site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_ss) %>% 
  rvest::html_table() %>% 
  dplyr::mutate(rank = "SS") %>% 
  tidyr::separate(`ポケモン`, into = c("name", "memo", "memo2")) %>% 
  dplyr::mutate(memo2 = dplyr::if_else(name == "アローラ", name, memo2),
                name = dplyr::if_else(name == "アローラ", memo, name),
                name = dplyr::if_else(!is.na(memo2),
                                      paste(name, "（", memo2, "の姿）", sep = ""),
                                      name),
                memo = dplyr::if_else(!is.na(memo2), memo2, memo)) %>% 
  dplyr::select(rank, name, type = `タイプ`, memo, CP = `最大CP`,
                skill = `おすすめわざ`) %>% 
  tidyr::separate(skill, c("skill", "type1", "skill1", "type2", "skill2"),
                  sep = "([【】])") %>% 
  dplyr::select(-skill)) %>% 
  DT::datatable()
```

## Rank S
```{r}
(rank_s <- site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_s) %>% 
  rvest::html_table() %>% 
  dplyr::mutate(rank = "S") %>% 
  tidyr::separate(`ポケモン`, into = c("name", "memo", "memo2")) %>% 
  dplyr::mutate(memo2 = dplyr::if_else(name == "アローラ", name, memo2),
                name = dplyr::if_else(name == "アローラ", memo, name),
                name = dplyr::if_else(!is.na(memo2),
                                      paste(name, "（", memo2, "の姿）", sep = ""),
                                      name),
                memo = dplyr::if_else(!is.na(memo2), memo2, memo)) %>% 
  dplyr::select(rank, name, type = `タイプ`, memo, CP = `最大CP`,
                skill = `おすすめわざ`) %>% 
  tidyr::separate(skill, c("skill", "type1", "skill1", "type2", "skill2"),
                  sep = "([【】])") %>% 
  dplyr::select(-skill)) %>% 
  DT::datatable()
```

## Rank A+
```{r}
(rank_ap <- site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_ap) %>% 
  rvest::html_table() %>% 
  dplyr::mutate(rank = "A+") %>% 
  tidyr::separate(`ポケモン`, into = c("name", "memo", "memo2")) %>% 
  dplyr::mutate(memo2 = dplyr::if_else(name == "アローラ", name, memo2),
                name = dplyr::if_else(name == "アローラ", memo, name),
                name = dplyr::if_else(!is.na(memo2),
                                      paste(name, "（", memo2, "の姿）", sep = ""),
                                      name),
                memo = dplyr::if_else(!is.na(memo2), memo2, memo)) %>% 
  dplyr::select(rank, name, type = `タイプ`, memo, CP = `最大CP`,
                skill = `おすすめわざ`) %>% 
  tidyr::separate(skill, c("skill", "type1", "skill1", "type2", "skill2"),
                  sep = "([【】])") %>% 
  dplyr::select(-skill)) %>% 
  DT::datatable()
```

## Rank A
```{r}
(rank_a <- site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_a) %>% 
  rvest::html_table() %>% 
  dplyr::mutate(rank = "A") %>% 
  tidyr::separate(`ポケモン`, into = c("name", "memo", "memo2")) %>% 
  dplyr::mutate(memo2 = dplyr::if_else(name == "アローラ", name, memo2),
                name = dplyr::if_else(name == "アローラ", memo, name),
                name = dplyr::if_else(!is.na(memo2),
                                      paste(name, "（", memo2, "の姿）", sep = ""),
                                      name),
                memo = dplyr::if_else(!is.na(memo2), memo2, memo)) %>% 
  dplyr::select(rank, name, type = `タイプ`, memo, CP = `最大CP`,
                skill = `おすすめわざ`) %>% 
  tidyr::separate(skill, c("skill", "type1", "skill1", "type2", "skill2"),
                  sep = "([【】])") %>% 
  dplyr::select(-skill)) %>% 
  DT::datatable()
```

## Total
```{r}
(rank_all <- rank_ss %>% 
  dplyr::bind_rows(rank_s, rank_ap, rank_a)) %>% 
  DT::datatable()
```

## Cross Table
```{r}
cp_table <- rank_all %>% 
  dplyr::group_by(type) %>% 
  dplyr::summarise(CP = round(max(CP)))

rank_all %>% 
  dplyr::count(rank, type) %>% 
  tidyr::spread(key = rank, value = n) %>% 
  dplyr::left_join(cp_table, .) %>% 
  DT::datatable()
```

## Heat Map
```{r, fig.height=10}
rank_all %>% 
  dplyr::group_by(type, rank) %>% 
  dplyr::summarise(MaxCP = max(CP), MeanCP = round(mean(CP))) %>% 
  ggplot2::ggplot(ggplot2::aes(x = rank, y = type)) + 
    ggplot2::geom_tile(ggplot2::aes(fill = MeanCP)) + 
    ggplot2::geom_text(ggplot2::aes(label = MaxCP), colour = "#FFFFFF") +
    ggplot2::scale_fill_continuous(type = "viridis") +
    ggplot2::labs(subtitle = "白文字の数値は最大CP")
```

```{r}
rank_all %>% 
  dplyr::group_by(type, rank) %>% 
  dplyr::summarise(MaxCP = max(CP), MeanCP = round(mean(CP))) %>% 
  dplyr::mutate(text = dplyr::case_when(MaxCP > MeanCP ~ type, TRUE ~ "")) %>% 
  ggplot2::ggplot(ggplot2::aes(x = MeanCP, y = MaxCP)) + 
    ggplot2::geom_point(ggplot2::aes(colour = rank)) +
    ggrepel::geom_label_repel(ggplot2::aes(label = text, colour = rank))
```


# プロ野球

```{r, include=FALSE}
site_url <- "https://baseball.yahoo.co.jp/npb/standings/"
xpath_ce <- "//*[@id=\"sta_c\"]/div/table"
xpath_pa <- "//*[@id=\"sta_p\"]/div/table"
xpath_in <- "//*[@id=\"sta_i\"]/div/table"
xpath_op <- "//*[@id=\"sta_o\"]/div/table"
```

## セ・リーグ
```{r}
site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_ce) %>% 
  rvest::html_table() %>% 
  DT::datatable()
```

## パ・リーグ
```{r}
site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_pa) %>% 
  rvest::html_table() %>% 
  DT::datatable()
```

## 交流戦
```{r}
site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_in) %>% 
  rvest::html_table() %>% 
  DT::datatable()
```

## オープン戦
```{r}
site_url %>% 
  xml2::read_html() %>% 
  rvest::html_node(xpath = xpath_op) %>% 
  rvest::html_table() %>% 
  DT::datatable()
```


# 大相撲 平成30年11月場所
```{r, include=FALSE}
site_url <- "https://sports.yahoo.co.jp/sumo/torikumi/stats/?bashoId=201811&day="
```

## 幕内（中入り後）取組一覧
```{r, include=FALSE}
xpath_mu <- "//*[@id=\"makuuchi\"]/table"
```

```{r}
df <- purrr::map2(site_url, c(1:15), ~ paste(.x, .y, sep = "")) %>%
  purrr::map2_df(c(1:15), .f = function(.x, .y) {
    xml2::read_html(.x) %>% 
      rvest::xml_node(xpath = xpath_mu) %>%
      rvest::html_table(header = FALSE) %>%
      dplyr::slice(-1) %>% 
      dplyr::mutate(day = .y)})

result <- df %>% 
  tidyr::extract(X2, "e_name", regex = "([^[:digit:]]+)", remove = FALSE) %>% 
  tidyr::extract(X6, "w_name", regex = "([^[:digit:]]+)", remove = FALSE) %>% 
  tidyr::extract(X2, c("e_win", "e_lose"),
                 regex = "([[:digit:]])勝([[:digit:]])", remove = TRUE) %>% 
  tidyr::extract(X6, c("w_win", "w_lose"),
                 regex = "([[:digit:]])勝([[:digit:]])", remove = TRUE) %>% 
  dplyr::select(day, e_class = X1, e_name, e_win, e_lose, e_mark = X3,
                kimarite = X4, w_mark = X5, w_class = X7, w_name, w_win, w_lose)
  
result %>% DT::datatable()
```

## 十両取組一覧
```{r, include=FALSE}
xpath_mu <- "//*[@id=\"juryo\"]/table"
```

```{r}
df <- purrr::map2(site_url, c(1:15), ~ paste(.x, .y, sep = "")) %>%
  purrr::map2_df(c(1:15), .f = function(.x, .y) {
    xml2::read_html(.x) %>% 
      rvest::xml_node(xpath = xpath_mu) %>%
      rvest::html_table(header = FALSE) %>%
      dplyr::slice(-1) %>% 
      dplyr::mutate(day = .y)})

result <- df %>% 
  tidyr::extract(X2, "e_name", regex = "([^[:digit:]]+)", remove = FALSE) %>% 
  tidyr::extract(X6, "w_name", regex = "([^[:digit:]]+)", remove = FALSE) %>% 
  tidyr::extract(X2, c("e_win", "e_lose"),
                 regex = "([[:digit:]])勝([[:digit:]])", remove = TRUE) %>% 
  tidyr::extract(X6, c("w_win", "w_lose"),
                 regex = "([[:digit:]])勝([[:digit:]])", remove = TRUE) %>% 
  dplyr::select(day, e_class = X1, e_name, e_win, e_lose, e_mark = X3,
                kimarite = X4, w_mark = X5, w_class = X7, w_name, w_win, w_lose)
  
result %>% DT::datatable()
```


